name: spellbook_gmbh_frontend main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - run: npm ci
      
      - run: npm run build
        env: 
          CI: ""

  push_to_DockerHub:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spellbook_gmbh_frontend:latest
          build-args: |
            PORT=443
            NODE_VERSION=${{vars.NODE_VERSION}}
            HTTPS=true
            SSL_CRT_FILE_NAME=${{vars.SSL_CRT_FILE_NAME}}
            SSL_KEY_FILE_NAME=${{vars.SSL_KEY_FILE_NAME}}
            SSL_DIR=src/assets/ssl/prod

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: push_to_DockerHub

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with: 
          host: spellbook-gmbh.de
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          # create .env if not exists
          # write secrets
          # pull new image, remove left overs from old image, start microservice
          script: |
            if [ ! -f ./.env ]; then 
                touch ./.env;
            fi

            printf "REACT_APP_CRYPTO_KEY=${{secrets.REACT_APP_CRYPTO_KEY}}\n" >> ./.env
            printf "REACT_APP_CRYPTO_IV=${{secrets.REACT_APP_CRYPTO_IV}}\n" >> ./.env
            printf "SSL_KEY_PASSWORD=${{secrets.SSL_KEY_PASSWORD}}\n" >> ./.env

            docker compose pull frontend
            yes | docker rm $(docker container ls --all --filter=ancestor=$(docker images -f "dangling=true" -q) --format "{{.ID}}") --force
            yes | docker image rm $(docker images -f "dangling=true" -q)
            docker compose up -d